name = "ProbabilityTransports"
uuid = "6cb8f75d-6579-4ae3-8431-bc9b57364f63"
authors = ["Paul Tiede <ptiede91@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
